      # Warning: indentation here matters!

      # Pytorch MacOS builds
      - pytorch_macos_10_13_py3_build:
          requires:
            - setup
      - pytorch_macos_10_13_py3_test:
          requires:
            - setup
            - pytorch_macos_10_13_py3_build
      - pytorch_macos_10_13_cuda9_2_cudnn7_py3_build:
          requires:
            - setup

      # Pytorch Windows builds
      - pytorch_windows_ws2019_cuda10_1_cudnn7_py3:
          requires:
            - setup
